### PR TITLE
Simplify cert check for ssl connections

### PR DESCRIPTION
**Pull request by swerter**
Use the tls_certificate_check library to simplify ssl connections.

### CODE REVIEW

**Review by guenni68 — APPROVED** [review]

**Comment by swerter** [comment]
thanks!

**Comment by maxmarcon** [comment]
I recently had to integrate my Elixir application with an IMAP mailbox and this library saved me hours of hacking, thank you so much for building it!

This PR is very important to make sure that the TLS certificates are verified - any chance of a new version being released soon to include these changes?

Thanks!

**Comment by guenni68** [comment]
@maxmarcon I just released version 0.3.0

**Comment by maxmarcon** [comment]
fantastic! Thanks a ton!

**Pull request merged**
